server:
#  端口号
  port: 8085
spring:
  application:
#   应用名
    name: service-zuul
eureka:
  #eueka 地址
  instance:
    hostname: localhost
  client:
#    注册地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
zuul:
  routes:
    #网关名字随便起
    demo-customer:
#      网关url 端口后面的部分
      path: /test/**
      #映射的项目的spring.application.name
      serviceId: demo-customer
#    #有多个映射项目就重复操作
#    demo-customerb:
      ##      网关url 端口后面的部分
      #      path: /test/**
      #      #映射的项目的spring.application.name
      #      serviceId: demo-customer
  host:
    connect-timeout-millis: 15000 #HTTP连接超时大于Hystrix的超时时间
    socket-timeout-millis: 60000   #socket超时
ribbon:        #设置ribbon的超时时间小于zuul的超时时间
  ReadTimeout: 10000
  ConnectTimeout: 10000
#负载均衡配置
spring-boot-user:
  ribbon:
    listOfServices: http://127.0.0.1:8202,http://127.0.0.1:8201