server:
  port: 8202

spring:
  application:
    name: demo-customer

eureka:

  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
feign:
  hystrix:
    enabled: true
