server:
  port: 8091

eureka:
  #eueka 主机名
  instance:
    hostname: localhost
    #    每秒发一个心跳包
    lease-renewal-interval-in-seconds: 1
    #    告诉服务器2秒没有心跳，注销
    lease-expiration-duration-in-seconds: 2
  client:
    #提供者和消费者的注册地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  application:
    name: demo-provider

spring.datasource:
  name: develop
  url: jdbc:mysql://127.0.0.1:3306/yuepai?useUnicode=true&characterEncoding=utf8&autoReconnect=true
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver
  tomcat:
    max-active: 1200
    max-wait: 1000
    initial-wait : 500